### ISSUE TITLE
Where is the customer service file?

### ISSUE THREAD

**Issue by balramxyadav** [perseidesjs/medusa-plugin-otp#2]
To update and retrieve the OTP secret, we need an extended customer service that is mentioned in the example in the README, but I can't find the code anywhere.

**Comment by prakashrandy18** [comment]
@balramxyadav 

import CustomerService from '../services/customer'
const customerService = container.resolve<CustomerService>('customerService')

there is no docs for that..as it was mentioned as custom service, 

instead, i have tried to take existing medusa customer service by container DI , 
 
const customerService = container.resolve("customerService");

**Comment by adevinwild** [comment]
Hey @balramxyadav and @prakashrandy18 ! 👋
I've updated the docs !

Basically, you need to extend the `CustomerService` to make sure the `CustomerService.update` function will not throw a type error since it uses a specific input type ( [`UpdateCustomerInput`](https://github.com/medusajs/medusa/blob/v1.20.9/packages/medusa/src/types/customers.ts#L73) ) and that type does not contains the new field : `otp_secret`

Closing this issue, since it should now be much more clear 👍
